version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - mqtt
